---
- name: Run the dev-sec.ssh-hardening role and include custom vars
  become: true
  become_user: root
  remote_user: decoder
  hosts: webserver
  vars_files:
    - vars.yml
  roles:
    - dev-sec.ssh-hardening
  pre_tasks:
    - name: Generate ED25519 key if needed
      command: ssh-keygen -t ed25519 -f /etc/ssh/ssh_host_ed25519_key -N ""
      args:
        creates: /etc/ssh/ssh_host_ed25519_key
